### ISSUE TITLE
Баг с customtimer

### ISSUE THREAD

**Issue by pnpnewbie** [ScriptedSnark/agmod-client-updated-releases#1]
Если поставить customtimer на несколько секунд и умереть до того как он закончится он исчезнет.

**Comment by ScriptedSnark** [comment]
Об этой проблеме ещё год назад было известно, но я о ней напрочь забыл)

Спасибо, что напомнил, в следующем обновлении будет исправлено.

**Comment by ScriptedSnark** [comment]
Исправлено.
